create table if not exists
moviemp
(
    remessa uinteger,
    entidade varchar(4),
    orgao usmallint,
    uniorcam usmallint,
    funcao usmallint,
    subfuncao usmallint,
    programa usmallint,
    projativ usmallint,
    rubrica varchar(21),
    chave_empenho varchar(13),
    ano_empenho usmallint,
    entidade_empenho utinyint,
    nr_empenho usmallint,
    credor uinteger,
    caracteristica_peculiar usmallint,
    registro_precos char,
    nr_licitacao uinteger,
    ano_licitacao usmallint,
    historico varchar(400),
    forma_contratacao varchar(3),
    base_legal utinyint,
    despesa_funcionario char,
    licitacao_compartilhada char,
    cnpj_gerenciador varchar(18),
    exercicio_recurso utinyint,
    fonte_recurso usmallint,
    codigo_orcamentario usmallint,
    emenda_parlamentar usmallint,
    empenhado_bruto decimal(11, 2),
    estorno_empenho decimal(11, 2),
    empenhado decimal(11, 2),
    liquidado_bruto decimal(11, 2),
    estorno_liquidacao decimal(11, 2),
    liquidado decimal(11, 2),
    pago_bruto decimal(11, 2),
    estorno_pagamento decimal(11, 2),
    pago decimal(11, 2)
);

delete from moviemp where remessa = {{remessa}};

insert into moviemp
(
    remessa,
    entidade,
    orgao,
    uniorcam,
    funcao,
    subfuncao,
    programa,
    projativ,
    rubrica,
    chave_empenho,
    ano_empenho,
    entidade_empenho,
    nr_empenho,
    credor,
    caracteristica_peculiar,
    registro_precos,
    nr_licitacao,
    ano_licitacao,
    historico,
    forma_contratacao,
    base_legal,
    despesa_funcionario,
    licitacao_compartilhada,
    cnpj_gerenciador,
    exercicio_recurso,
    fonte_recurso,
    codigo_orcamentario,
    emenda_parlamentar,
    empenhado_bruto,
    estorno_empenho,
    empenhado,
    liquidado_bruto,
    estorno_liquidacao,
    liquidado,
    pago_bruto,
    estorno_pagamento,
    pago
)
select distinct
    remessa,
    entidade,
    orgao,
    uniorcam,
    funcao,
    subfuncao,
    programa,
    projativ,
    rubrica,
    chave_empenho,
    ano_empenho,
    entidade_empenho,
    nr_empenho,
    credor,
    caracteristica_peculiar,
    registro_precos,
    nr_licitacao,
    ano_licitacao,
    historico,
    forma_contratacao,
    base_legal,
    despesa_funcionario,
    licitacao_compartilhada,
    cnpj_gerenciador,
    exercicio_recurso,
    fonte_recurso,
    codigo_orcamentario,
    emenda_parlamentar,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
from empenho
where remessa = {{remessa}};

update moviemp m
set
    empenhado_bruto = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_empenho = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    empenhado = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho),
    liquidado_bruto = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_liquidacao = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    liquidado = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho),
    pago_bruto = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_pagamento = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    pago = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho)
where remessa = {{remessa}};