create table if not exists
moviemp
(
    remessa uinteger,
    entidade varchar(4),
    orgao usmallint,
    nome_orgao varchar(80),
    uniorcam usmallint,
    nome_uniorcam varchar(80),
    funcao usmallint,
    nome_funcao varchar(80),
    subfuncao usmallint,
    nome_subfuncao varchar(80),
    programa usmallint,
    nome_programa varchar(80),
    projativ usmallint,
    nome_projativ varchar(80),
    rubrica varchar(21),
    nome_rubrica varchar(110),
    chave_empenho varchar(13),
    ano_empenho usmallint,
    entidade_empenho utinyint,
    nr_empenho usmallint,
    credor uinteger,
    nome_credor varchar(60),
    caracteristica_peculiar usmallint,
    nome_caracteristica_peculiar varchar(30),
    registro_precos char,
    nr_licitacao uinteger,
    ano_licitacao usmallint,
    historico varchar(400),
    forma_contratacao varchar(3),
    nome_forma_contratacao varchar(30),
    base_legal utinyint,
    nome_base_legal varchar(30),
    despesa_funcionario char,
    nome_despesa_funcionario varchar(30),
    licitacao_compartilhada char,
    cnpj_gerenciador varchar(18),
    exercicio_recurso utinyint,
    nome_exercicio_recurso varchar(30),
    fonte_recurso usmallint,
    nome_fonte_recurso varchar(80),
    codigo_orcamentario usmallint,
    nome_codigo_orcamentario varchar(80),
    emenda_parlamentar usmallint,
    nome_emenda_parlamentar varchar(80),
    empenhado_bruto decimal(11, 2),
    estorno_empenho decimal(11, 2),
    empenhado decimal(11, 2),
    liquidado_bruto decimal(11, 2),
    estorno_liquidacao decimal(11, 2),
    liquidado decimal(11, 2),
    pago_bruto decimal(11, 2),
    estorno_pagamento decimal(11, 2),
    pago decimal(11, 2)
);

delete from moviemp where remessa = {{remessa}};

insert into moviemp
(
    remessa,
    entidade,
    orgao,
    uniorcam,
    funcao,
    subfuncao,
    programa,
    projativ,
    rubrica,
    chave_empenho,
    ano_empenho,
    entidade_empenho,
    nr_empenho,
    credor,
    caracteristica_peculiar,
    registro_precos,
    nr_licitacao,
    ano_licitacao,
    historico,
    forma_contratacao,
    base_legal,
    despesa_funcionario,
    licitacao_compartilhada,
    cnpj_gerenciador,
    exercicio_recurso,
    fonte_recurso,
    codigo_orcamentario,
    emenda_parlamentar,
    empenhado_bruto,
    estorno_empenho,
    empenhado,
    liquidado_bruto,
    estorno_liquidacao,
    liquidado,
    pago_bruto,
    estorno_pagamento,
    pago
)
select distinct
    remessa,
    entidade,
    orgao,
    uniorcam,
    funcao,
    subfuncao,
    programa,
    projativ,
    rubrica,
    chave_empenho,
    ano_empenho,
    entidade_empenho,
    nr_empenho,
    credor,
    caracteristica_peculiar,
    registro_precos,
    nr_licitacao,
    ano_licitacao,
    historico,
    forma_contratacao,
    base_legal,
    despesa_funcionario,
    licitacao_compartilhada,
    cnpj_gerenciador,
    exercicio_recurso,
    fonte_recurso,
    codigo_orcamentario,
    emenda_parlamentar,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
from empenho
where remessa = {{remessa}};

update moviemp m
set
    empenhado_bruto = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_empenho = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    empenhado = (select sum(valor) from empenho where remessa = m.remessa and chave_empenho = m.chave_empenho),
    liquidado_bruto = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_liquidacao = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    liquidado = (select sum(valor) from liquidacao where remessa = m.remessa and chave_empenho = m.chave_empenho),
    pago_bruto = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho and valor > 0),
    estorno_pagamento = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho and valor < 0),
    pago = (select sum(valor) from pagamento where remessa = m.remessa and chave_empenho = m.chave_empenho)
where remessa = {{remessa}};

update moviemp t
set
    nome_orgao = (select nome from orgao where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and orgao = t.orgao limit 1),
    nome_uniorcam = (select nome from uniorcam where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and uniorcam = t.uniorcam limit 1),
    nome_funcao = (select nome from funcao where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and funcao = t.funcao limit 1),
    nome_subfuncao = (select nome from subfuncao where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and subfuncao = t.subfuncao limit 1),
    nome_programa = (select nome from programa where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and programa = t.programa limit 1),
    nome_projativ = (select nome from projativ where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and projativ = t.projativ limit 1),
    nome_rubrica = (select especificacao from rubrica where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and rubrica like t.rubrica limit 1),
    nome_credor = (select nome from credor where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and credor = t.credor limit 1),
    nome_caracteristica_peculiar = (select nome from caracteristica_peculiar where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and caracteristica_peculiar = t.caracteristica_peculiar limit 1),
    nome_forma_contratacao = (select nome from forma_contratacao where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and forma_contratacao like t.forma_contratacao limit 1),
    nome_base_legal = (select nome from base_legal where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and base_legal = t.base_legal limit 1),
    nome_despesa_funcionario = (select nome from despesa_funcionario where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and despesa_funcionario like t.despesa_funcionario limit 1),
    nome_exercicio_recurso = (select nome from exercicio_recurso where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and exercicio_recurso = t.exercicio_recurso limit 1),
    nome_fonte_recurso = (select nome from fonte_recurso where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and fonte_recurso = t.fonte_recurso limit 1),
    nome_codigo_orcamentario = (select nome from codigo_orcamentario where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and codigo_orcamentario = t.codigo_orcamentario limit 1),
    nome_emenda_parlamentar = (select nome from emenda_parlamentar where exercicio = cast(substring(cast(t.remessa as varchar(6)), 1, 4) as usmallint) and emenda_parlamentar = t.emenda_parlamentar limit 1)
where nome_orgao is null or nome_orgao like '';
